/***************************************************************
* file: HangmanGame.java
* author: Marco Roman
* class: CS 245 – GUI Development
*
* assignment: program 1
* date last modified: 1/24/17
*
* purpose: This program creates a hangman game that randomly selects a word
* unknown to the user and allows the user to guess the word letter by letter,
* applying penalties where necessary.
*
****************************************************************/ 
package my.HangmanUI;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Random;
import static java.lang.Thread.sleep;
import javax.swing.JComponent;

//This class houses the entire game and handles the creation of the interface
public class HangmanGame extends javax.swing.JFrame {
    
    
    static StringBuilder words[] = {new StringBuilder("abstract"), 
                                    new StringBuilder("cemetery"),
                                    new StringBuilder("nurse"),
                                    new StringBuilder("pharmacy"),
                                    new StringBuilder("climbing")};
    static StringBuilder spaces = new StringBuilder();
    
    Random gen = new Random();
    
    String word = words[gen.nextInt(5)].toString();
    static char letter = ' ';
    
    static int points = 100; 
    int anatomy = 0;
    
    /**
     * Creates new form HangmanGame
     */
    public HangmanGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonA = new javax.swing.JButton();
        ButtonB = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        ButtonD = new javax.swing.JButton();
        ButtonH = new javax.swing.JButton();
        ButtonI = new javax.swing.JButton();
        ButtonJ = new javax.swing.JButton();
        ButtonK = new javax.swing.JButton();
        ButtonL = new javax.swing.JButton();
        ButtonM = new javax.swing.JButton();
        ButtonN = new javax.swing.JButton();
        ButtonO = new javax.swing.JButton();
        ButtonP = new javax.swing.JButton();
        ButtonQ = new javax.swing.JButton();
        ButtonE = new javax.swing.JButton();
        ButtonF = new javax.swing.JButton();
        ButtonG = new javax.swing.JButton();
        ButtonR = new javax.swing.JButton();
        ButtonS = new javax.swing.JButton();
        ButtonT = new javax.swing.JButton();
        ButtonU = new javax.swing.JButton();
        ButtonV = new javax.swing.JButton();
        ButtonW = new javax.swing.JButton();
        ButtonX = new javax.swing.JButton();
        ButtonY = new javax.swing.JButton();
        ButtonZ = new javax.swing.JButton();
        timeDisplay = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        score = new javax.swing.JTextField();
        wordDisplay = new javax.swing.JLabel();
        skipButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("HangmanGame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        ButtonA.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonA.setText("A");
        ButtonA.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonA.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonA.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAActionPerformed(evt);
            }
        });

        ButtonB.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonB.setText("B");
        ButtonB.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonB.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonB.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBActionPerformed(evt);
            }
        });

        ButtonC.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonC.setText("C");
        ButtonC.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonC.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonC.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });

        ButtonD.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonD.setText("D");
        ButtonD.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonD.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonD.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDActionPerformed(evt);
            }
        });

        ButtonH.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonH.setText("H");
        ButtonH.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonH.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonH.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHActionPerformed(evt);
            }
        });

        ButtonI.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonI.setText("I");
        ButtonI.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonI.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonI.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIActionPerformed(evt);
            }
        });

        ButtonJ.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonJ.setText("J");
        ButtonJ.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonJ.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonJ.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJActionPerformed(evt);
            }
        });

        ButtonK.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonK.setText("K");
        ButtonK.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonK.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonK.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKActionPerformed(evt);
            }
        });

        ButtonL.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonL.setText("L");
        ButtonL.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonL.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonL.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLActionPerformed(evt);
            }
        });

        ButtonM.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonM.setText("M");
        ButtonM.setMaximumSize(new java.awt.Dimension(41, 25));
        ButtonM.setMinimumSize(new java.awt.Dimension(41, 25));
        ButtonM.setPreferredSize(new java.awt.Dimension(41, 25));
        ButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMActionPerformed(evt);
            }
        });

        ButtonN.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonN.setText("N");
        ButtonN.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonN.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonN.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNActionPerformed(evt);
            }
        });

        ButtonO.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonO.setText("O");
        ButtonO.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonO.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonO.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOActionPerformed(evt);
            }
        });

        ButtonP.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonP.setText("P");
        ButtonP.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonP.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonP.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPActionPerformed(evt);
            }
        });

        ButtonQ.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonQ.setText("Q");
        ButtonQ.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonQ.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonQ.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonQActionPerformed(evt);
            }
        });

        ButtonE.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonE.setText("E");
        ButtonE.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonE.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonE.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEActionPerformed(evt);
            }
        });

        ButtonF.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonF.setText("F");
        ButtonF.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonF.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonF.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFActionPerformed(evt);
            }
        });

        ButtonG.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonG.setText("G");
        ButtonG.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonG.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonG.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGActionPerformed(evt);
            }
        });

        ButtonR.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonR.setText("R");
        ButtonR.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonR.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonR.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRActionPerformed(evt);
            }
        });

        ButtonS.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonS.setText("S");
        ButtonS.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonS.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonS.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSActionPerformed(evt);
            }
        });

        ButtonT.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonT.setText("T");
        ButtonT.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonT.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonT.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTActionPerformed(evt);
            }
        });

        ButtonU.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonU.setText("U");
        ButtonU.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonU.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonU.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUActionPerformed(evt);
            }
        });

        ButtonV.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonV.setText("V");
        ButtonV.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonV.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonV.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVActionPerformed(evt);
            }
        });

        ButtonW.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonW.setText("W");
        ButtonW.setMargin(new java.awt.Insets(1, 0, 1, 0));
        ButtonW.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonW.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonW.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWActionPerformed(evt);
            }
        });

        ButtonX.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonX.setText("X");
        ButtonX.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonX.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonX.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXActionPerformed(evt);
            }
        });

        ButtonY.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonY.setText("Y");
        ButtonY.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonY.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonY.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonYActionPerformed(evt);
            }
        });

        ButtonZ.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        ButtonZ.setText("Z");
        ButtonZ.setMaximumSize(new java.awt.Dimension(40, 25));
        ButtonZ.setMinimumSize(new java.awt.Dimension(40, 25));
        ButtonZ.setPreferredSize(new java.awt.Dimension(40, 25));
        ButtonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonZActionPerformed(evt);
            }
        });

        Thread clock = new Thread(){
            public void run(){
                try{
                    while(true){
                        Calendar calendar = new GregorianCalendar();
                        String hourZ = "", minZ = "", secZ = "";

                        int day = calendar.get(Calendar.DAY_OF_MONTH);

                        int month = calendar.get(Calendar.MONTH);
                        ++month;

                        int year = calendar.get(Calendar.YEAR);

                        int hour = calendar.get(Calendar.HOUR);
                        if(hour == 0)
                        hour = 12;
                        if(hour < 10)
                        hourZ = "0";

                        int minute = calendar.get(Calendar.MINUTE);
                        if(minute < 10)
                        minZ = "0";

                        int second = calendar.get(Calendar.SECOND);
                        if(second < 10)
                        secZ = "0";

                        timeDisplay.setText((month) + "/" + day + "/" + year + "  " + hourZ + hour + ":" + minZ + minute + ":" + secZ + second);
                        sleep(1000);
                    }
                }catch(InterruptedException e){
                    e.printStackTrace();
                }
            }
        };

        clock.start();
        timeDisplay.setEditable(false);
        timeDisplay.setText("jTextField1");

        title.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        title.setText("HANGMAN");

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel1.setText("Score:");

        score.setText(Integer.toString(points));

        wordDisplay.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        spaces.delete(0, spaces.toString().length());

        for(int i = 0; i < word.length(); ++i){
            spaces.append("_ ");
        }
        wordDisplay.setText(spaces.toString());

        skipButton.setLabel("Skip");
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(3, 3, 3)
                                        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(skipButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(title)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(timeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(wordDisplay)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(skipButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(wordDisplay)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //The following methods all handle the events that follow any letter being clicked
    //On a correct guess, the appropriate blank space is filled in on the JFrame
    //On an incorrect guess, 10 points are deducted from the score a body part is drawn
    //In either case, the button is disabled after it is clicked
    private void ButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAActionPerformed
        ButtonA.setEnabled(false);
        letter = 'a';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonAActionPerformed

    private void ButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBActionPerformed
        ButtonB.setEnabled(false);
        letter = 'b';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonBActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        ButtonC.setEnabled(false);
        letter = 'c';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonCActionPerformed

    private void ButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDActionPerformed
        ButtonD.setEnabled(false);
        letter = 'd';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonDActionPerformed

    private void ButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEActionPerformed
        ButtonE.setEnabled(false);
        letter = 'e';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonEActionPerformed

    private void ButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFActionPerformed
        ButtonF.setEnabled(false);
        letter = 'f';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonFActionPerformed

    private void ButtonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGActionPerformed
        ButtonG.setEnabled(false);
        letter = 'g';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonGActionPerformed

    private void ButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHActionPerformed
        ButtonH.setEnabled(false);
        letter = 'h';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonHActionPerformed

    private void ButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIActionPerformed
        ButtonI.setEnabled(false);
        letter = 'i';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonIActionPerformed

    private void ButtonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJActionPerformed
        ButtonJ.setEnabled(false);
        letter = 'j';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonJActionPerformed

    private void ButtonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKActionPerformed
        ButtonK.setEnabled(false);
        letter = 'k';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonKActionPerformed

    private void ButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLActionPerformed
        ButtonL.setEnabled(false);
        letter = 'l';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonLActionPerformed

    private void ButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMActionPerformed
        ButtonM.setEnabled(false);
        letter = 'm';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonMActionPerformed

    private void ButtonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNActionPerformed
        ButtonN.setEnabled(false);
        letter = 'n';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonNActionPerformed

    private void ButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOActionPerformed
        ButtonO.setEnabled(false);
        letter = 'o';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonOActionPerformed

    private void ButtonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPActionPerformed
        ButtonP.setEnabled(false);
        letter = 'p';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonPActionPerformed

    private void ButtonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonQActionPerformed
        ButtonQ.setEnabled(false);
        letter = 'q';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonQActionPerformed

    private void ButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRActionPerformed
        ButtonR.setEnabled(false);
        letter = 'r';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonRActionPerformed

    private void ButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSActionPerformed
        ButtonS.setEnabled(false);
        letter = 's';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonSActionPerformed

    private void ButtonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTActionPerformed
        ButtonT.setEnabled(false);
        letter = 't';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonTActionPerformed

    private void ButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUActionPerformed
        ButtonU.setEnabled(false);
        letter = 'u';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonUActionPerformed

    private void ButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVActionPerformed
        ButtonV.setEnabled(false);
        letter = 'v';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonVActionPerformed

    private void ButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWActionPerformed
        ButtonW.setEnabled(false);
        letter = 'w';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonWActionPerformed

    private void ButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonXActionPerformed
        ButtonX.setEnabled(false);
        letter = 'x';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonXActionPerformed

    private void ButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonYActionPerformed
        ButtonY.setEnabled(false);
        letter = 'y';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonYActionPerformed

    private void ButtonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonZActionPerformed
        ButtonZ.setEnabled(false);
        letter = 'z';
        
        if(!containsLetter(letter)){
            penalty();
        }
    }//GEN-LAST:event_ButtonZActionPerformed

    //This method exits the game and transitions to the score page
    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed
        //MainScreen ms = new MainScreen();
        //ms.setVisible(true);
        ColorGame colorGame = new ColorGame();
        colorGame.setVisible(true);
        colorGame.addMouseListener(colorGame);
        this.setVisible(false);
    }//GEN-LAST:event_skipButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangmanGame().setVisible(true);
            }
        });
    }
    
    //Method: penalty
    //Deducts 10 points from the score for an incorrect guess and increments the counter
    //indicating how many body parts have been drawn. It also checks whether the user has
    //Completed the hanged man or has lost too many points
    public void penalty(){
        points -= 10;
        ++anatomy;
        
        if(points <= 0 || anatomy >= 6){
            //HighScoresScreen hs = new HighScoresScreen();
            //hs.setVisible(true);
            ColorGame colorGame = new ColorGame();
            colorGame.setVisible(true);
            colorGame.addMouseListener(colorGame);
            this.setVisible(false);
        }       
        
        score.setText(Integer.toString(points));
        repaint();
    }
    
    //Method: paint
    //Draws the scaffold in the form and checks which body part should
    //be drawn to the screen
    @Override
    public void paint(Graphics g){
        
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;
        Line2D lin = new Line2D.Float(260, 65, 380, 65);
        Line2D lin2 = new Line2D.Float(260, 65, 260, 230);
        Line2D lin3 = new Line2D.Float(380, 65, 380, 90);
        Line2D lin4 = new Line2D.Float(190, 230, 450, 230);
        g2.draw(lin);
        g2.draw(lin2);
        g2.draw(lin3);
        g2.draw(lin4);
        
        Line2D torso = new Line2D.Float(380, 130, 380, 185);
        Line2D rightArm = new Line2D.Float(380, 135, 400, 155);
        Line2D leftArm = new Line2D.Float(380, 135, 360, 155);
        Line2D rightLeg = new Line2D.Float(380, 185, 400, 205);
        Line2D leftLeg = new Line2D.Float(380, 185, 360, 205);
        
        //Draws parts of the hanged man based on the value of the anatomy variable
        
        switch(anatomy){
            case 1: g2.drawOval(360, 90, 40, 40);
                break;
            case 2:
                g2.drawOval(360, 90, 40, 40);
                g2.draw(torso);
                break;
            case 3:
                g2.drawOval(360, 90, 40, 40);
                g2.draw(torso);
                g2.draw(rightArm);
                break;
            case 4:
                g2.drawOval(360, 90, 40, 40);
                g2.draw(torso);
                g2.draw(rightArm);
                g2.draw(leftArm);
                break;
            case 5:
                g2.drawOval(360, 90, 40, 40);
                g2.draw(torso);
                g2.draw(rightArm);
                g2.draw(leftArm);
                g2.draw(rightLeg);
                break;
            case 6:
                g2.drawOval(360, 90, 40, 40);
                g2.draw(torso);
                g2.draw(rightArm);
                g2.draw(leftArm);
                g2.draw(rightLeg);
                g2.draw(leftLeg);
                break;
            default: break;                        
        }
    }
    
    //Method: containsLetter
    //Checks the user's selected letter against the unknown word to determine whether the
    //guess was correct. Also checks whether the user has guessed the complete word
    public boolean containsLetter(char letter){
        boolean contains = false;
        
        for(int i = 0; i < word.length(); ++i){
            if(letter == word.charAt(i)){
                contains = true;
                spaces.deleteCharAt(i * 2);
                spaces.insert(i * 2, letter);
                wordDisplay.setText(spaces.toString());
                repaint();
                if(complete())
                    winner();
            }                
        }
        return contains;
    }
    
    //Method: complete
    //Checks whether the entire unknown word has been guessed
    public static boolean complete(){
        for(int i = 0; i < spaces.length(); ++i){
            if(spaces.charAt(i) == '_')
                return false;
        }
        
        points = 100;
        return true;
    }
    
    //Method: winner
    //Transitions out of the game and to the appropriate screen in the event of a win
    public void winner(){     
        //HighScoresScreen hs = new HighScoresScreen();
        //hs.setVisible(true);
        ColorGame colorGame = new ColorGame();
        colorGame.setVisible(true);
        colorGame.addMouseListener(colorGame);
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonA;
    private javax.swing.JButton ButtonB;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonD;
    private javax.swing.JButton ButtonE;
    private javax.swing.JButton ButtonF;
    private javax.swing.JButton ButtonG;
    private javax.swing.JButton ButtonH;
    private javax.swing.JButton ButtonI;
    private javax.swing.JButton ButtonJ;
    private javax.swing.JButton ButtonK;
    private javax.swing.JButton ButtonL;
    private javax.swing.JButton ButtonM;
    private javax.swing.JButton ButtonN;
    private javax.swing.JButton ButtonO;
    private javax.swing.JButton ButtonP;
    private javax.swing.JButton ButtonQ;
    private javax.swing.JButton ButtonR;
    private javax.swing.JButton ButtonS;
    private javax.swing.JButton ButtonT;
    private javax.swing.JButton ButtonU;
    private javax.swing.JButton ButtonV;
    private javax.swing.JButton ButtonW;
    private javax.swing.JButton ButtonX;
    private javax.swing.JButton ButtonY;
    private javax.swing.JButton ButtonZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField score;
    private java.awt.Button skipButton;
    private javax.swing.JTextField timeDisplay;
    private javax.swing.JLabel title;
    private static javax.swing.JLabel wordDisplay;
    // End of variables declaration//GEN-END:variables
}