/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.HangmanUI;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.Writer;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathanquiros
 */
public class EndScreen extends javax.swing.JFrame {
    private static String score = Integer.toString(SudokuGame.score);

    /**
     * Creates new form EndScreen
     */
    public EndScreen() {
        initComponents();
        System.out.println("This is the score" + score);
        playerScore.setText(score);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corePanel = new javax.swing.JPanel();
        yourScore = new javax.swing.JLabel();
        playerScore = new javax.swing.JLabel();
        endButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 400));

        corePanel.setBackground(new java.awt.Color(0, 0, 0));
        corePanel.setSize(new java.awt.Dimension(600, 400));

        yourScore.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        yourScore.setForeground(new java.awt.Color(255, 0, 51));
        yourScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yourScore.setText("Your Score");
        yourScore.setToolTipText("Player Score");

        playerScore.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        playerScore.setForeground(new java.awt.Color(255, 255, 255));
        playerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerScore.setText("score");

        endButton.setBackground(new java.awt.Color(0, 0, 0));
        endButton.setText("End");
        endButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout corePanelLayout = new javax.swing.GroupLayout(corePanel);
        corePanel.setLayout(corePanelLayout);
        corePanelLayout.setHorizontalGroup(
            corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corePanelLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yourScore, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(playerScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(210, 210, 210))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(endButton)
                .addGap(40, 40, 40))
        );
        corePanelLayout.setVerticalGroup(
            corePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(yourScore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(endButton)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMain() {
        MainScreen ms = new MainScreen();
        ms.setVisible(true);
        this.setVisible(false);
    }
    
    private void endButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endButtonMouseClicked
        int result = JOptionPane.showOptionDialog(null, "Do you want to submit your score?", "Submit",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (result == JOptionPane.YES_OPTION) {
            String userName = JOptionPane.showInputDialog("Input your username as 3 letters:");
            try {
                File f = new File(System.getProperty("user.dir"));
                System.out.println(System.getProperty("user.dir"));
                if(f.exists()) {
                    Writer output;
                    output = new BufferedWriter(new FileWriter("scores.txt", true));
                    output.append(userName + "\n");
                    output.append(score + "\n");
                    output.close();
                    backToMain();
                } else {
                    PrintWriter writer = new PrintWriter("scores.txt", "UTF-8");
                    writer.println(userName);
                    writer.println(score);
                    writer.close();
                    backToMain();
                }
            } catch(Exception e) {
                System.out.println("End button error: " + e);
            }
        } else if (result == JOptionPane.NO_OPTION) {
            backToMain();
        }
    }//GEN-LAST:event_endButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel corePanel;
    private javax.swing.JButton endButton;
    private javax.swing.JLabel playerScore;
    private javax.swing.JLabel yourScore;
    // End of variables declaration//GEN-END:variables
}
