/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowtest;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Station 4
 */
public class JPanel1 extends javax.swing.JPanel {

    
    private int [] key = {8,3,5,4,1,6,9,2,7,2,9,6,8,5,7,4,3,1,4,1,7,2,9,3,6,5,
        8,5,6,9,1,3,4,7,8,2,1,2,3,6,7,8,5,4,9,7,4,8,5,2,9,1,6,3,6,5,2,7,8,1,3,
        9,4,9,8,1,3,4,5,2,7,6,3,7,4,9,6,2,8,1,5};
    /**
     * Creates new form JPanel1
     */
    public JPanel1() {
        initComponents();
    }
    
    private void checkKey(JFormattedTextField t, int x){
        boolean result = false;
        int guess = Integer.parseInt(t.getText());
        if(key[x-1] == guess){
            t.setForeground(Color.BLUE);
        }
        else{
            t.setForeground(Color.RED);
        }
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        g.setColor(Color.BLACK);
        for(int i=0, x=8; i<4; i++, x+=114){
            g.drawLine(x, 28, x, 370);
        }
        for (int i = 0, y = 28; i < 4; i++, y += 114) {
            g.drawLine(8, y, 350, y);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jFormattedTextField17 = new javax.swing.JFormattedTextField();
        jFormattedTextField18 = new javax.swing.JFormattedTextField();
        jFormattedTextField19 = new javax.swing.JFormattedTextField();
        jFormattedTextField20 = new javax.swing.JFormattedTextField();
        jFormattedTextField21 = new javax.swing.JFormattedTextField();
        jFormattedTextField22 = new javax.swing.JFormattedTextField();
        jFormattedTextField23 = new javax.swing.JFormattedTextField();
        jFormattedTextField24 = new javax.swing.JFormattedTextField();
        jFormattedTextField25 = new javax.swing.JFormattedTextField();
        jFormattedTextField26 = new javax.swing.JFormattedTextField();
        jFormattedTextField27 = new javax.swing.JFormattedTextField();
        jFormattedTextField28 = new javax.swing.JFormattedTextField();
        jFormattedTextField29 = new javax.swing.JFormattedTextField();
        jFormattedTextField30 = new javax.swing.JFormattedTextField();
        jFormattedTextField31 = new javax.swing.JFormattedTextField();
        jFormattedTextField32 = new javax.swing.JFormattedTextField();
        jFormattedTextField33 = new javax.swing.JFormattedTextField();
        jFormattedTextField34 = new javax.swing.JFormattedTextField();
        jFormattedTextField35 = new javax.swing.JFormattedTextField();
        jFormattedTextField36 = new javax.swing.JFormattedTextField();
        jFormattedTextField37 = new javax.swing.JFormattedTextField();
        jFormattedTextField38 = new javax.swing.JFormattedTextField();
        jFormattedTextField39 = new javax.swing.JFormattedTextField();
        jFormattedTextField40 = new javax.swing.JFormattedTextField();
        jFormattedTextField41 = new javax.swing.JFormattedTextField();
        jFormattedTextField42 = new javax.swing.JFormattedTextField();
        jFormattedTextField43 = new javax.swing.JFormattedTextField();
        jFormattedTextField44 = new javax.swing.JFormattedTextField();
        jFormattedTextField45 = new javax.swing.JFormattedTextField();
        jFormattedTextField46 = new javax.swing.JFormattedTextField();
        jFormattedTextField47 = new javax.swing.JFormattedTextField();
        jFormattedTextField48 = new javax.swing.JFormattedTextField();
        jFormattedTextField49 = new javax.swing.JFormattedTextField();
        jFormattedTextField50 = new javax.swing.JFormattedTextField();
        jFormattedTextField51 = new javax.swing.JFormattedTextField();
        jFormattedTextField52 = new javax.swing.JFormattedTextField();
        jFormattedTextField53 = new javax.swing.JFormattedTextField();
        jFormattedTextField54 = new javax.swing.JFormattedTextField();
        jFormattedTextField55 = new javax.swing.JFormattedTextField();
        jFormattedTextField56 = new javax.swing.JFormattedTextField();
        jFormattedTextField57 = new javax.swing.JFormattedTextField();
        jFormattedTextField58 = new javax.swing.JFormattedTextField();
        jFormattedTextField59 = new javax.swing.JFormattedTextField();
        jFormattedTextField60 = new javax.swing.JFormattedTextField();
        jFormattedTextField61 = new javax.swing.JFormattedTextField();
        jFormattedTextField62 = new javax.swing.JFormattedTextField();
        jFormattedTextField63 = new javax.swing.JFormattedTextField();
        jFormattedTextField64 = new javax.swing.JFormattedTextField();
        jFormattedTextField65 = new javax.swing.JFormattedTextField();
        jFormattedTextField66 = new javax.swing.JFormattedTextField();
        jFormattedTextField67 = new javax.swing.JFormattedTextField();
        jFormattedTextField68 = new javax.swing.JFormattedTextField();
        jFormattedTextField69 = new javax.swing.JFormattedTextField();
        jFormattedTextField70 = new javax.swing.JFormattedTextField();
        jFormattedTextField71 = new javax.swing.JFormattedTextField();
        jFormattedTextField72 = new javax.swing.JFormattedTextField();
        jFormattedTextField73 = new javax.swing.JFormattedTextField();
        jFormattedTextField74 = new javax.swing.JFormattedTextField();
        jFormattedTextField75 = new javax.swing.JFormattedTextField();
        jFormattedTextField76 = new javax.swing.JFormattedTextField();
        jFormattedTextField77 = new javax.swing.JFormattedTextField();
        jFormattedTextField78 = new javax.swing.JFormattedTextField();
        jFormattedTextField79 = new javax.swing.JFormattedTextField();
        jFormattedTextField80 = new javax.swing.JFormattedTextField();
        jFormattedTextField81 = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setText("8");
        jFormattedTextField1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        jFormattedTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jFormattedTextField4.setEditable(false);
        jFormattedTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField4.setText("4");
        jFormattedTextField4.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField4ActionPerformed(evt);
            }
        });

        jFormattedTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField5.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });

        jFormattedTextField6.setEditable(false);
        jFormattedTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField6.setText("6");
        jFormattedTextField6.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField7.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField8.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField9.setEditable(false);
        jFormattedTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField9.setText("7");
        jFormattedTextField9.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField10.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField11.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField12.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField13.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField14.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField15.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField16.setEditable(false);
        jFormattedTextField16.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField16.setText("4");
        jFormattedTextField16.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField17.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField18.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField19.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField20.setEditable(false);
        jFormattedTextField20.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField20.setText("1");
        jFormattedTextField20.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField21.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField22.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField23.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField24.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField25.setEditable(false);
        jFormattedTextField25.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField25.setText("6");
        jFormattedTextField25.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField26.setEditable(false);
        jFormattedTextField26.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField26.setText("5");
        jFormattedTextField26.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField27.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField28.setEditable(false);
        jFormattedTextField28.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField28.setText("5");
        jFormattedTextField28.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField28ActionPerformed(evt);
            }
        });

        jFormattedTextField29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField29.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField30.setEditable(false);
        jFormattedTextField30.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField30.setText("9");
        jFormattedTextField30.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField31.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField32.setEditable(false);
        jFormattedTextField32.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField32.setText("3");
        jFormattedTextField32.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField33.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField34.setEditable(false);
        jFormattedTextField34.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField34.setText("7");
        jFormattedTextField34.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField34ActionPerformed(evt);
            }
        });

        jFormattedTextField35.setEditable(false);
        jFormattedTextField35.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField35.setText("8");
        jFormattedTextField35.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField35ActionPerformed(evt);
            }
        });

        jFormattedTextField36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField36.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField37.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField38.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField39.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField40.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField40.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField41.setEditable(false);
        jFormattedTextField41.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField41.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField41.setText("7");
        jFormattedTextField41.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField42.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField42.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField43.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField43.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField44.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField44.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField45.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField46.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField47.setEditable(false);
        jFormattedTextField47.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField47.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField47.setText("4");
        jFormattedTextField47.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField48.setEditable(false);
        jFormattedTextField48.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField48.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField48.setText("8");
        jFormattedTextField48.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField49.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField49.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField50.setEditable(false);
        jFormattedTextField50.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField50.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField50.setText("2");
        jFormattedTextField50.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField51.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField51.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField52.setEditable(false);
        jFormattedTextField52.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField52.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField52.setText("1");
        jFormattedTextField52.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField52ActionPerformed(evt);
            }
        });

        jFormattedTextField53.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField53.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField54.setEditable(false);
        jFormattedTextField54.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField54.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField54.setText("3");
        jFormattedTextField54.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField54ActionPerformed(evt);
            }
        });

        jFormattedTextField55.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField55.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField56.setEditable(false);
        jFormattedTextField56.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField56.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField56.setText("5");
        jFormattedTextField56.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField57.setEditable(false);
        jFormattedTextField57.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField57.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField57.setText("2");
        jFormattedTextField57.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField58.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField58.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField59.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField59.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField60.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField60.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField61.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField61.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField62.setEditable(false);
        jFormattedTextField62.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField62.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField62.setText("9");
        jFormattedTextField62.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField63.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField63.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField64.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField64.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField65.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField65.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField66.setEditable(false);
        jFormattedTextField66.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField66.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField66.setText("1");
        jFormattedTextField66.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jFormattedTextField66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField66ActionPerformed(evt);
            }
        });

        jFormattedTextField67.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField67.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField68.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField68.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField69.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField69.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField70.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField70.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField71.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField71.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField72.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField72.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField73.setEditable(false);
        jFormattedTextField73.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField73.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField73.setText("3");
        jFormattedTextField73.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField74.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField74.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField75.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField75.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField76.setEditable(false);
        jFormattedTextField76.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField76.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField76.setText("9");
        jFormattedTextField76.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField77.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField77.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField78.setEditable(false);
        jFormattedTextField78.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField78.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField78.setText("2");
        jFormattedTextField78.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField79.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField79.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField80.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField80.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jFormattedTextField81.setEditable(false);
        jFormattedTextField81.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField81.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormattedTextField81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField81.setText("5");
        jFormattedTextField81.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField74, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField59, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField66, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField67, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField68, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField69, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField79, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField59, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField66, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField67, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField68, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField69, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField74, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField79, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void jFormattedTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField4ActionPerformed

    private void jFormattedTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField34ActionPerformed

    private void jFormattedTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField35ActionPerformed

    private void jFormattedTextField52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField52ActionPerformed

    private void jFormattedTextField54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField54ActionPerformed

    private void jFormattedTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField28ActionPerformed

    private void jFormattedTextField66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField66ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
        checkKey(jFormattedTextField2, 2);
        jFormattedTextField2 = null;
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
        checkKey(jFormattedTextField3, 3);
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField20;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField23;
    private javax.swing.JFormattedTextField jFormattedTextField24;
    private javax.swing.JFormattedTextField jFormattedTextField25;
    private javax.swing.JFormattedTextField jFormattedTextField26;
    private javax.swing.JFormattedTextField jFormattedTextField27;
    private javax.swing.JFormattedTextField jFormattedTextField28;
    private javax.swing.JFormattedTextField jFormattedTextField29;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField30;
    private javax.swing.JFormattedTextField jFormattedTextField31;
    private javax.swing.JFormattedTextField jFormattedTextField32;
    private javax.swing.JFormattedTextField jFormattedTextField33;
    private javax.swing.JFormattedTextField jFormattedTextField34;
    private javax.swing.JFormattedTextField jFormattedTextField35;
    private javax.swing.JFormattedTextField jFormattedTextField36;
    private javax.swing.JFormattedTextField jFormattedTextField37;
    private javax.swing.JFormattedTextField jFormattedTextField38;
    private javax.swing.JFormattedTextField jFormattedTextField39;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField40;
    private javax.swing.JFormattedTextField jFormattedTextField41;
    private javax.swing.JFormattedTextField jFormattedTextField42;
    private javax.swing.JFormattedTextField jFormattedTextField43;
    private javax.swing.JFormattedTextField jFormattedTextField44;
    private javax.swing.JFormattedTextField jFormattedTextField45;
    private javax.swing.JFormattedTextField jFormattedTextField46;
    private javax.swing.JFormattedTextField jFormattedTextField47;
    private javax.swing.JFormattedTextField jFormattedTextField48;
    private javax.swing.JFormattedTextField jFormattedTextField49;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField50;
    private javax.swing.JFormattedTextField jFormattedTextField51;
    private javax.swing.JFormattedTextField jFormattedTextField52;
    private javax.swing.JFormattedTextField jFormattedTextField53;
    private javax.swing.JFormattedTextField jFormattedTextField54;
    private javax.swing.JFormattedTextField jFormattedTextField55;
    private javax.swing.JFormattedTextField jFormattedTextField56;
    private javax.swing.JFormattedTextField jFormattedTextField57;
    private javax.swing.JFormattedTextField jFormattedTextField58;
    private javax.swing.JFormattedTextField jFormattedTextField59;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField60;
    private javax.swing.JFormattedTextField jFormattedTextField61;
    private javax.swing.JFormattedTextField jFormattedTextField62;
    private javax.swing.JFormattedTextField jFormattedTextField63;
    private javax.swing.JFormattedTextField jFormattedTextField64;
    private javax.swing.JFormattedTextField jFormattedTextField65;
    private javax.swing.JFormattedTextField jFormattedTextField66;
    private javax.swing.JFormattedTextField jFormattedTextField67;
    private javax.swing.JFormattedTextField jFormattedTextField68;
    private javax.swing.JFormattedTextField jFormattedTextField69;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField70;
    private javax.swing.JFormattedTextField jFormattedTextField71;
    private javax.swing.JFormattedTextField jFormattedTextField72;
    private javax.swing.JFormattedTextField jFormattedTextField73;
    private javax.swing.JFormattedTextField jFormattedTextField74;
    private javax.swing.JFormattedTextField jFormattedTextField75;
    private javax.swing.JFormattedTextField jFormattedTextField76;
    private javax.swing.JFormattedTextField jFormattedTextField77;
    private javax.swing.JFormattedTextField jFormattedTextField78;
    private javax.swing.JFormattedTextField jFormattedTextField79;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField80;
    private javax.swing.JFormattedTextField jFormattedTextField81;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    // End of variables declaration//GEN-END:variables
}
